//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHang.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Orders
    {
        public TB_Orders()
        {
            this.TB_OrderDetails = new HashSet<TB_OrderDetails>();
        }
    
        public int OrderId { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> OrderProviderId { get; set; }
        public Nullable<int> OrderUserId { get; set; }
    
        public virtual ICollection<TB_OrderDetails> TB_OrderDetails { get; set; }
        public virtual TB_Providers TB_Providers { get; set; }
        public virtual TB_Users TB_Users { get; set; }
    }
}
