//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHang.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Providers
    {
        public TB_Providers()
        {
            this.TB_Orders = new HashSet<TB_Orders>();
            this.TB_Products = new HashSet<TB_Products>();
        }
    
        public int ProviderId { get; set; }
        public string ProviderName { get; set; }
        public string ProviderAddress { get; set; }
        public string ProviderPhone { get; set; }
        public string ProviderEmail { get; set; }
        public string ProviderNote { get; set; }
        public Nullable<int> ProviderStatus { get; set; }
        public string Logo { get; set; }
    
        public virtual ICollection<TB_Orders> TB_Orders { get; set; }
        public virtual ICollection<TB_Products> TB_Products { get; set; }
    }
}
